### ISSUE TITLE
Generated static page results in an error for IE 11/Edge

### ISSUE THREAD

**Issue by jmyrland** [ymmooot/nuxt-jsonld#10]
When the page is generated statically, the statically rendered pages does not work in IE11/edge due to this package. The error `SCRIPT1028: SCRIPT1028: Expected identifier, string or number` is thrown, and it is related to this section of code:

![image](https://user-images.githubusercontent.com/837651/54839910-1b812a80-4ccc-11e9-960a-01ac6edcb8c1.png)

As you see, the spread operator (`...`) is used, which is not supported in IE/edge. I am assuming that the serverside generated script is also included in the client side bundle - but I am not sure.

Do you have any workarounds regarding this?

I have tried adding 
```
    transpile: [
      'nuxt-jsonld',
    ],
```
to the build config, but another error was thrown instead:
`Assignment to read-only properties is not allowed in strict mode`

I also tried adding the plugin with `ssr: false`, but that failed as well.

If you got any other tips, please let me know :)

**Comment by ilyaskorik** [comment]
What with this issue?

**Comment by ymmooot** [comment]
I will fix this. Please wait for it:pray:

**Comment by ymmooot** [comment]
I add babel setting for ie11.
The transpiled files have been published since `v0.0.7`.
