### ISSUE TITLE
Support Nuxt v3.0.0 (stable)

### ISSUE THREAD

**Issue by thijsw** [ymmooot/nuxt-jsonld#1014]
**Describe the bug**
When I'm trying to use this module with the (just released) stable 3.0.0 version I get the following error:

```
Error while requiring module nuxt-jsonld: SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'
```

**Your Nuxt version**
3.0.0

**Your nuxt-jsonld version**
latest

**Comment by kstraszewski** [comment]
Same here

**Comment by MyWay** [comment]
Which should be related to https://github.com/nuxt/framework/pull/9029

**Comment by quamsta** [comment]
Added a PR that should resolve this.

**Comment by ymmooot** [comment]
Thank you all 🙏 
v2.0.7 has been released.
