### ISSUE TITLE
Is is safe to use this plugin ?

### ISSUE THREAD

**Issue by besnikh** [ymmooot/nuxt-jsonld#11]
According to: 
[https://github.com/nuxt/vue-meta#__dangerouslydisablesanitizersbytagid-string]

The **__dangerouslydisablesanitizersbytagid** will open the possibility to XSS Attacks.. how safe it is to use the way that you are using in your plugin? 

Just asking since I need to use your plugin and was wondering.

Cheers

**Comment by ymmooot** [comment]
Hello @besnikh.
This plugin makes disable sanitize only **your json-ld**.
It does not affect any your data by vue-meta.

That is why, if your json-ls that made by your `json` method is safe, it is save.
Do not output user's input that is not validated with `json` method.
