### ISSUE TITLE
Generates multiple script tags since 1.5.4

### ISSUE THREAD

**Issue by ohbarye** [ymmooot/nuxt-jsonld#1104]
**Describe the bug**
Since nuxt-jsonld 1.5.4, my Nuxt app has generated multiple script tags. Before or equal to 1.5.3, there was only one script tag.

**Your Nuxt version**
2.15.8

**Your nuxt-jsonld version**
1.5.4 (even 1.5.5 as well)

**To Reproduce**

1. Open https://codesandbox.io/p/sandbox/laughing-sound-hs128w?file=%2Fcomponents%2FFaqSection.vue
2. Open terminal by clicking + button on right-top
    - <img width="678" alt="image" src="https://user-images.githubusercontent.com/1811616/220394393-b317fad5-acbc-4d9f-89a7-90458eebf33d.png">
3. Run `yarn generate`
4. Run `less dist/index.html | grep nuxt-jsonld`

Then you'll see 2 `<script>` tags for nuxt-jsonld.

<details>
<summary>Outdated comment</summary>

For the meantime, I put my project's setting (it's partial... Sorry.).

Please give me some time to reproduce the problem on [codesandbox.io](https://codesandbox.io/), I'm still not sure what're the minimum procedures. 🙏 

```js
// nuxt.config.js
export default {
  plugins: ['~/plugins/jsonld'],
  ...
}
```

```js
// plugins/jsonld.js
import Vue from 'vue'
import NuxtJsonld from 'nuxt-jsonld'

Vue.use(NuxtJsonld)
```

```js
// FaqSection.vue
<template>
  <section :class="classes">
        <ul class="_list">
          <li v-for="(faq, index) in faqs" :key="index" class="_item">
            <a
              v-if="faq.url"
              :href="`${faq.url}`"
              :class="`ga-link ${faq.param}`"
              v-html="faq.title"
            />
            <div class="_accordion" v-else>
              <input type="checkbox" :id="`faq_${index}`" class="_input" />
              <label :for="`faq_${index}`" class="_label">
                {{ faq.title }}
              </label>
              <div class="_content">
                <div class="_text" v-html="faq.text" />
              </div>
            </div>
          </li>
        </ul>
  </section>
</template>

<script>
export default {
  name: 'FaqSection',
  props: {
    faqs: {
      type: Array,
      required: true,
    },
  },
  jsonld() {
    const items = this.faqs.map(item => ({
      '@type': 'Question',
      name: item.title,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.text,
      },
    }));
    return {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: items,
    };
  },
};
</script>
```

This `FaqSection.vue` is used in 7 pages. I expect every page should have only one script tag for jsonld like the one below and it was so before 1.5.4.

```html
<script data-n-head="ssr" data-hid="nuxt-jsonld-6beb7c40" type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [...]
}
</script>
```

But some pages got to have 1~7 script tags since 1.5.4.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1811616/220240425-0de050f3-2c3e-4195-b3de-a67ed440bd67.png">

</details>

**Screenshots**

A generated HTML has multiple script tags. I think it should be only one.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1811616/220394583-607426fb-a0a2-42e7-ba74-bf0f140550b5.png">

**Additional context**

I'm unfamiliar with its internal implementation, https://github.com/ymmooot/nuxt-jsonld/commit/5077cf2c9c9e2bf97e67e2fb66250c9dc07efe1e might be the cause..? There seem to be [quite few diff between 1.5.3 and 1.5.4](https://github.com/ymmooot/nuxt-jsonld/compare/v1.5.3...v1.5.4)

(Added) Once I remove the `computed` option, it does not reproduce.

**Comment by ohbarye** [comment]
@ymmooot 
I'm still not sure whether it is a minimum reproduction, but I added an example app on CodeSandbox. I'd be glad if you check it when you have time.

**Comment by ymmooot** [comment]
Hi @ohbarye, thank you for your reporting and the reproduction link.
I understood the issue and will fix it soon.
Please use an older version that works fine until fixed 🙏

**Comment by ymmooot** [comment]
I have just released v1.5.6.
Please try it and tell me if something wrong.

**Comment by ohbarye** [comment]
Thanks for your quick fix. I'll try to check if it's resolved. 👍

**Comment by ohbarye** [comment]
@ymmooot Sorry for my late reply, and our team confirmed v1.5.6 resolved this issue. I'm closing with many thanks!
