### ISSUE TITLE
[Bug Report] Issue if "head" is already set. In example vuetify.js does not work with nuxt-jsonld

### ISSUE THREAD

**Issue by oanstein** [ymmooot/nuxt-jsonld#112]
## Related
https://github.com/vuetifyjs/vuetify/issues/8855#issuecomment-528318381

## Problem
It breaks with other code and packages if they also have "head" set

## Reproduction Link
https://codesandbox.io/s/codesandbox-nuxt-8tbth

## Other comments
The mixin in https://github.com/ymmooot/nuxt-jsonld/blob/master/src/createMixin.ts probably overrides what Vuetify does. Maybe it's possible to take into account that head could already be set, either object or function.

**Comment by ymmooot** [comment]
@oanstein Thank you for reporting.
I will take care of this ASAP.
Please wait for a new version.
