### ISSUE TITLE
Duplicate meta tags added by nuxt-jsonld on nuxt 2.16

### ISSUE THREAD

**Issue by Zsavajji** [ymmooot/nuxt-jsonld#1124]
Hi,
after updating to `nuxt-jsonld 1.5.6` i started getting reports of duplicate meta tags on my static nuxt site.
I tracked down the bug to nuxt-jsonld, which seems to add a copy of all the meta information by itself.
I did not have much time to investigate the issue, but it seems related to your latest commits.
I'm not using `@nuxt/bridge`, as i understand it's relevant in the context of head generation.

Let me know if i can be of some more help.

nuxt 2.16 - nuxt-jsonld 1.5.6

<img width="1455" alt="version1 5 6" src="https://user-images.githubusercontent.com/6460348/225561852-5181f3b4-828a-436e-9fe1-d4833cfc3217.png">
With version 1.5.6

<img width="1427" alt="version1 5 5" src="https://user-images.githubusercontent.com/6460348/225561870-63572629-db07-4a2f-8f6a-2b4939c1a4f6.png">
With version 1.5.5

Thanks!w

**Comment by arkhamvm** [comment]
@ymmooot Hi, I have issue that can be relative to this fix. 
I have two components with `jsonld()` method, Article and Breadcrumb.
Breadcrumb component is a child of Article.
On page I see only Breadcrumb `ld+json` script.
If I remove `jsonld()` method in Breadcrumb component, I see Article `ld+json` script.
I need both of them. How can I achieve that?
