### ISSUE TITLE
Failed to resolve import "#head" error in Nuxt 3.4.1

### ISSUE THREAD

**Issue by thijsw** [ymmooot/nuxt-jsonld#1149]
**Describe the bug**
When using this module with the latest version of Nuxt, I get these errors:

```
 ERROR  Failed to resolve import "#head" from "node_modules/nuxt-jsonld/dist/runtime/plugin.mjs?v=bf2fd235". Does the file exist?

 ERROR  Failed to resolve import "#head" from "node_modules/nuxt-jsonld/dist/runtime/composable.mjs?v=bf2fd235". Does the file exist?
```

**Your Nuxt version**
3.4.1

**Your nuxt-jsonld version**
`nuxt-jsonld` version.

**To Reproduce**
Install the depependency in a Nuxt project and run the project

**Comment by ymmooot** [comment]
Hi @thijsw @palachX, thank you for reporting.
I wil fix it asap.

**Comment by ymmooot** [comment]
ref #1151

**Comment by ymmooot** [comment]
Hi @thijsw @palachX.
I have released new version that fixies the issue.
Please update to `v2.0.8` and tell me if still not working.

**Comment by palachX** [comment]
> Hi @thijsw @palachX. I have released new version that fixies the issue. Please update to `v2.0.8` and tell me if still not working.

Best of the best
thx u
