### ISSUE TITLE
Schema Not Present But Only For Products

### ISSUE THREAD

**Issue by dan-thesill** [ymmooot/nuxt-jsonld#1267]
**Describe the bug**
JSON LD present on some pages, but not on others after updating Nuxt version. Ecommerce website, our sitewide organization jsonld shows up, our article schema shows up, but product schema doesn't appear.

Even if I test a really basic static json to see if it's to do with the format, it doesn't work. Any idea why that would happen?

**Your Nuxt version**
    "nuxt": "^2.17.0",

**Your nuxt-jsonld version**
    "nuxt-jsonld": "^1.5.7",

**To Reproduce**
Sorry, can't provide code sandbox.

**Additional context**
In the mean time, I'm using this and it works.

```
  head() {
    return {
      script: [
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify(this.jsonld())
        }
      ],
      __dangerouslyDisableSanitizers: ['script']
    }
  },
```

**Comment by ymmooot** [comment]
How do you use `nuxt-jsonld` to show the product schema?

**Comment by ymmooot** [comment]
no response
