### ISSUE TITLE
Safari throws when parsing JSON-LD

### ISSUE THREAD

**Issue by codeofsumit** [ymmooot/nuxt-jsonld#1280]
**Describe the bug**
Safari throws error on any page using structured data.

**Your Nuxt version**
2.17.0

**Your nuxt-jsonld version**
1.5.7

**To Reproduce**
Create an test.html and include the following code

```html
<html>
  <head>
    <script type="application/ld+json">
      [
        {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Parqet",
          "url": "https://www.parqet.com/",
          "logo": "https://www.parqet.com/logos/parqet_logo_pos.svg",
          "sameAs": [
            "https://www.facebook.com/parqetcom",
            "https://twitter.com/ParqetApp",
            "https://www.instagram.com/ParqetApp/",
            "https://www.youtube.com/channel/UC4LOcElG8Z73Hvgbbp3m1KQ",
            "https://www.linkedin.com/company/parqet/",
            "https://github.com/tresorone"
          ]
        }
      ]
    </script>
  </head>
  <body>
    test
  </body>
</html>
```
Open in Safari in Mac and look into the console.

**Screenshots**
![image](https://github.com/ymmooot/nuxt-jsonld/assets/2399810/8ebfdbb2-7705-4b4e-adae-2d876def3bbc)

**Additional context**
Also asked on StackOverflow
https://stackoverflow.com/questions/76995140/safari-throws-when-parsing-json-ld

**Comment by codeofsumit** [comment]
It looks like this is fixed when returning an object and using the @graph notation instead of an array.
https://github.com/ymmooot/nuxt-jsonld/issues/247

```html
<html>
  <head>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@graph": [
          {
            "@type": "Organization",
            "name": "Parqet",
            "url": "https://www.parqet.com/",
            "logo": "https://www.parqet.com/logos/parqet_logo_pos.svg"
          }
        ]
      }
    </script>
  </head>
  <body>
    test
  </body>
</html>
```

Does this make sense?

**Comment by ymmooot** [comment]
Hi @codeofsumit.

https://www.w3.org/TR/json-ld11/#example-19-using-multiple-contexts

An array of objects is valid in JSON-LD. I suspect it's a Safari issue.
You can also verify it using Google's [Rich Results Test tool](https://search.google.com/test/rich-results).
Thus, Googlebot can parse it.

If you still think there's a problem, you can use `@graph` as you said.

**Comment by codeofsumit** [comment]
> Hi @codeofsumit.
> 
> https://www.w3.org/TR/json-ld11/#example-19-using-multiple-contexts
> 
> An array of objects is valid in JSON-LD. I suspect it's a Safari issue. You can also verify it using Google's [Rich Results Test tool](https://search.google.com/test/rich-results). Thus, Googlebot can parse it.
> 
> If you still think there's a problem, you can use `@graph` as you said.

Yes I'm aware it's valid. Safari still throws though (test it yourself with the above code).

@ymmooot I'm wondering, does this library have any downsides re @graph compared to an array of objects? E.g. are JSON-LD definitions from parent-child pages merged together or do they overwrite each other?

**Comment by ymmooot** [comment]
> Yes I'm aware it's valid. Safari still throws though (test it yourself with the above code).

"Yes, I've tested it and confirmed the issue.
`nuxt-jsonld` is still working despite the Safari error, so I don't believe it's a major concern.

The implementation of this library doesn't distinguish between @graph and an array of objects. It simply displays the provided JSON-LD.

**Comment by ymmooot** [comment]
@codeofsumit Thank you for your reporting. 👍 

It's certainly not good to pollute the sentry log.
I will add a description to the README.md regarding the Safari error.
