### ISSUE TITLE
How can i use this with  to generate multiple json schema on a single page?

### ISSUE THREAD

**Issue by papakay** [ymmooot/nuxt-jsonld#136]
Please i need information on how to generate multiple json schema on a single page. Thank you.
.

**Comment by marvinhuebner** [comment]
Yes, I just want to have that too, seems not to be possible at the moment.

**Comment by ymmooot** [comment]
You can use `json` method from multiple components, then you will get multiple `<script type="application/ld+json"></script>` tags.

**Comment by asajadian** [comment]
We add `jsonld`s to main page component. I think adding it to another component is not the right way to achieve this, you may lose track of them. I believe there must be an option to add all in one `jsonld` method.

**Comment by ymmooot** [comment]
Hi @asajadian 
You can make multiple json in your main page component.
See this issue https://github.com/ymmooot/nuxt-jsonld/issues/247

**Comment by asajadian** [comment]
Hi @ymmooot 
That's cool. Thanks!
