### ISSUE TITLE
Generation probably only works in components and not in pages

### ISSUE THREAD

**Issue by marvinhuebner** [ymmooot/nuxt-jsonld#137]
I have the problem that the generation apparently only works in components and not in page components, is that so or do you have to do something extra? 

I wanted to create an example on CodeSandBox, but unfortunately it doesn't work here for some reason: https://codesandbox.io/s/nuxtjs-json-ld-example-mtwxu?fontsize=14&module=%2Fcomponents%2FLogo.vue

Thanks for the module and your help in advance!

**Comment by ymmooot** [comment]
@marvinhuebner
`jsonld` method of page components also generates JSON-LD tag without doing anything extra.
The codesandbox reproduction link looks working and two JSON-LD is showing up correctly.

![image](https://user-images.githubusercontent.com/28696621/66042046-548d3800-e556-11e9-9657-1200c2d97e00.png)

**Comment by marvinhuebner** [comment]
Now it works also for me. 

It looks like you have to restart the dev task, I guess I just didn't do that because nuxt actually reloads the config when I change something.

Will close the issue. Sorry for the interruption.

**Comment by ymmooot** [comment]
@marvinhuebner 
Sounds good. Thank you for using my plugin 👍
