### ISSUE TITLE
Doesn't work inside another composable after data fetching

### ISSUE THREAD

**Issue by TheDutchCoder** [ymmooot/nuxt-jsonld#1445]
**Describe the bug**
When using `useJsonld` inside of another composable and you fetch data, this jsonld composable fails to add data.
This _might_ be a Nuxt internal problem (with useHead => unhead)

**Your Nuxt version**
3.12.4

**Your nuxt-jsonld version**
2.0.8

**To Reproduce**
Steps to reproduce the behavior.
Repro: https://stackblitz.com/edit/github-pp3ujf?file=pages%2Fpage2.vue

Page 1 works, Page 2 doesn't.

**Comment by ymmooot** [comment]
Hi @TheDutchCoder, sorry for the late reply.

Please take a look at my example:
	•	[context.vue](https://github.com/ymmooot/nuxt-jsonld/blob/master/packages/example/pages/context.vue)
	•	[dog.ts](https://github.com/ymmooot/nuxt-jsonld/blob/master/packages/example/composables/dog.ts)

You can try it out by cloning the repository and running yarn && yarn workspace example dev.
It should work as expected!
