### ISSUE TITLE
Question - Can you layer / override the Jsonld()

### ISSUE THREAD

**Issue by khrome83** [ymmooot/nuxt-jsonld#20]
What I mean by this is - 

Can I have a default Jsonld() in `/layouts/default.vue`. Then in my `/pages/some-page.vue` append or overright any existing data in that object that default.vue is used as a base?

The benefit I see from this is several fold.

1. Items like organization type, search type are global to the site.
2. Things like breadcrumbs or product descriptions are specific to a product page or content page.

Google SEO is hard. =)

**Comment by ymmooot** [comment]
You can not overwrite it, but you can share your jsonld by importing it.

```js
// defaultJson.js
export default {
  '@context': 'http://schema.org',
  '@type': 'WebSite',
    url: 'https://example.com',
    name: 'cat and dog',
    publisher: {
        '@type': 'Organization',
        name: 'ymmooot'
    }
}
```

```js
// /pages/SomePage.vue
<script>
import defaultJson from '~/jsonlds/defaultJson'

export default {
  jsonld() {
    return {
      ...defaultJson,
      headline: 'some page title',
      description: 'some page description',
    }
  }
</script>
```

**Comment by khrome83** [comment]
That was going to be my fallback. Sounds good, thank you!
