### ISSUE TITLE
Random hid issue

### ISSUE THREAD

**Issue by ymmooot** [ymmooot/nuxt-jsonld#219]
# what is going on

This plugin uses `hid` to allow raw HTML string for innerHTML of JSON-LD script tag.
This `hid` will be changed every request to server or every generate static site.
It means ETag is changed every time even though contents are totally same.

# note
It reported in #58.
I fixed it by making hash for hid, but it was too heavy to use in large component.
So I revert it in #218.

**Comment by TrurlMcByte** [comment]
Changing HID making rehash all page on server, change ETag, and download page again. It's more heavy operations. Try to use hash by only part of jsonld (for example only first 1-2 levels). Usually it's enough. But need more investigation and review
