### ISSUE TITLE
How to return several json-ld scripts?

### ISSUE THREAD

**Issue by arkhamvm** [ymmooot/nuxt-jsonld#247]
Hi. I need to return two json-ld scripts - `Article` and `BreadcrumbList` which can't be joined one to each other, so i need two sepeated script tags in one component.
How i can do it?

**Comment by madsh93** [comment]
I need to know this as well. Hopefully somebody can help us out 👍

**Comment by ymmooot** [comment]
You can use `@graph` to dump multi structured data in one script tag.
Check this out 👉  [named-graphs](https://www.w3.org/TR/2014/REC-json-ld-20140116/#named-graphs).

You can confirm that the following JSON-LD is valid with [Structured Data Testing Tool - Google](https://search.google.com/structured-data/testing-tool/u/0/).

```js
{
  "@context": "http://schema.org",
  "@graph":
  [
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "item": {
            "@id": "https://example.com/articles/1",
            "name": "foo"
          }
        }
      ]
    },
    {
      "@type": "NewsArticle",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://google.com/article"
      },
      "headline": "Article headline",
      "image": [
        "https://example.com/photos/1x1/photo.jpg",
        "https://example.com/photos/4x3/photo.jpg",
        "https://example.com/photos/16x9/photo.jpg"
      ],
      "datePublished": "2015-02-05T08:00:00+08:00",
      "dateModified": "2015-02-05T09:20:00+08:00",
      "author": {
        "@type": "Person",
        "name": "John Doe"
      },
      "publisher": {
        "@type": "Organization",
        "name": "Google",
        "logo": {
          "@type": "ImageObject",
          "url": "https://google.com/logo.jpg"
        }
      },
      "description": "A most wonderful article"
    }
  ]
}
```

**Comment by arkhamvm** [comment]
Thanks! I was missed out `@graph` notation.

**Comment by madsh93** [comment]
Works like a charm. Thank you ymmooot 💃

**Comment by adarshmadrecha** [comment]
@ymmooot add this issue link or this solution in the readem.md file of the repo.
I am sure man users will be having this question.

**Comment by ymmooot** [comment]
@adarshmadrecha I added the description to the README.md https://github.com/ymmooot/nuxt-jsonld/commit/01e5fab73efb9d948f3eea1ac4ad8b8ecfc9b98f
