### ISSUE TITLE
Using jsonld() removes all other content from the head of the website

### ISSUE THREAD

**Issue by Alex61NN5** [ymmooot/nuxt-jsonld#3]
Hi There,

I added this package as described and when you use this package it removes all existing meta tags specified in the `nuxt.config.js` file

This happens on your example project also, this makes this package pretty much **unusable**

**Comment by p1pchenk0** [comment]
I think, issue is in this line:
`if (!this.$options || typeof this.$options.jsonld !== 'function')`

**Comment by RomanNagornyi** [comment]
> Hi There,
> 
> I added this package as described and when you use this package it removes all existing meta tags specified in the `nuxt.config.js` file
> 
> This happens on your example project also, this makes this package pretty much **unusable**

Agree with you Alex. I have the same issue

**Comment by ymmooot** [comment]
Thank you @Alex61NN5 @RomanNagornyi 
I will fix this asap 🙏
