### ISSUE TITLE
this.getMeta is not a function

### ISSUE THREAD

**Issue by subjacked** [ymmooot/nuxt-jsonld#341]
Since version 1.4.6 I get this error in the frontend. I call the jsonld method in my wildcard page _.vue file. With version 1.4.5 everyhting worked as expected. Additionally it shows a warning:

Error in beforeCreate hook: "TypeError: this.getMeta is not a function"

![image](https://user-images.githubusercontent.com/2064769/79874934-3c451380-83e9-11ea-857a-4a007b5a491c.png)

**Comment by ymmooot** [comment]
sorry about it.
please use v1.4.5 
I'm working on it.

This is happening for the same reason as https://github.com/ymmooot/nuxt-jsonld/issues/342.

**Comment by ymmooot** [comment]
sorry about it.
please use v1.4.5 
I'm working on it.

This is happening for the same reason as https://github.com/ymmooot/nuxt-jsonld/issues/342.

**Comment by subjacked** [comment]
For me the problem is still present even with 1.4.8
