### ISSUE TITLE
v1.4.6: Error in beforeCreate hook: "TypeError: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by LuXDAmore** [ymmooot/nuxt-jsonld#342]
Hi! ✋ 

I have something like this:

```javascript

    // Mixin
    export default {
        head() {
 
            return this.$store.state.cms.head;

        },
    };

```

and after updating from `v1.4.5` to `v1.4.6`, i'm getting this errors:

> Error in beforeCreate hook: "TypeError: Cannot read property 'state' of undefined".
> Uncaught TypeError: Cannot read property 'concat' of undefined at VueComponent.stringifyLDFn (mergeHead.js?0f45:26)

___

_Getting back to v1.4.5, It works properly_

**Comment by ymmooot** [comment]
Hi! @LuXDAmore ✋ 
Thank you for your speedy reporting.
I am working on this issue!

**Comment by LuXDAmore** [comment]
Thank you for the rapid fix!! 🚀 

_That problem was fixed, but another one comes.._

```javascript

// Mixin
export default {
    head() {

        const ACTIVE_PAGINATION = this.pagination.page + 1;

    },
};

```

> Cannot read property 'page' of undefined.

This is a mixin in a page, and `this.pagination.page` is coming from the asyncData method 🤔

On `v1.4.5` still no errors

**Comment by ymmooot** [comment]
Thank you again and sorry for not working versions.
I am fixing this issue ASAP.

**Comment by LuXDAmore** [comment]
Don't worry! I can keep the v1.4.5 😎 , take your time!  :)

Thank you for your fantastic work!  💪
