### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined after upgrade to 1.4.8 from 1.4.5

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [ymmooot/nuxt-jsonld#348]
After I've upgraded from 1.4.5 to 1.4.8 I've started to get this issue which seems to not be related to the specific data of my app but rather some internal issue of the lib
https://take.ms/1YULd

**Comment by ymmooot** [comment]
same reason of error as #347

**Comment by AndrewBogdanovTSS** [comment]
Seems to be working fine after upgrade to 1.4.9. Thanks 👍
