### ISSUE TITLE
Can't install v. 1.4.6 or 1.4.7

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [ymmooot/nuxt-jsonld#349]
When I try to manually install v.1.4.6 for testing - I get this message from yarn https://take.ms/0ui3m
it also suggests me to install a v.2.0.0 which doesn't exist in the `nuxt-jsonld` repo. Is it safe to install?

**Comment by ymmooot** [comment]
2.0.0 was published by mistake.
Please use 1.4.8.

**Comment by AndrewBogdanovTSS** [comment]
@ymmooot can't use it since it has issues I described in #348

**Comment by ymmooot** [comment]
Please use v1.4.5 🙇

**Comment by ymmooot** [comment]
https://github.com/ymmooot/nuxt-jsonld/issues/347#issuecomment-618887985
