### ISSUE TITLE
Support for Composition Api ?

### ISSUE THREAD

**Issue by Epistol** [ymmooot/nuxt-jsonld#408]
Any support for the new composition api ?

**Comment by ymmooot** [comment]
I am going to make a function for then new composition api.
Please wait for it. Or pull requests are always welcome!

**Comment by DavidGolodetsky** [comment]
I don't see the PR was merged. Is this composable is available now?

**Comment by ymmooot** [comment]
The code in the PR does not work right. 
Not available yet.

**Comment by lazercaveman** [comment]
Anything new about this???

**Comment by ymmooot** [comment]
I have release the new version of `nuxt-jsonld` and it has composition api.
I have no plans to make composition api for Nuxt2 at this time.
Let's move on Nuxt3 :pray:
