### ISSUE TITLE
[SSR] jsonld method seems to be called twice

### ISSUE THREAD

**Issue by samicodesit** [ymmooot/nuxt-jsonld#498]
I'm working on a Nuxt.js app in universal mode

On my `_sku` page I have:

```javascript
  methods: {
    getPrice() {
      console.log('----- Calling getPrice method -----');
      const price = this.product.sale_price;
      return +price.toFixed(2);
    },
  },
  jsonld() {
    return {
      '@context': 'http://schema.org',
      '@type': 'Product',
      name: this.product.name,
      offers: {
        '@type': 'Offer',
        priceCurrency: 'USD',
        price: this.getPrice(),
      },
    };
  },
```

I get `----- Calling getPrice method -----` showing on both my terminal (server)
then followed by another `----- Calling getPrice method -----` on my browser console (client)

**Comment by ymmooot** [comment]
What version are you using?

**Comment by ymmooot** [comment]
`jsonld` method runs as part of the `head` method.
`head` method runs on both server and client side.
