### ISSUE TITLE
Possible to load on a per-component basis?

### ISSUE THREAD

**Issue by t1mwillis** [ymmooot/nuxt-jsonld#564]
The documentation for using this with Nuxt specifies setting up a global plugin as follows:
```
// plugins/jsonld.js
import Vue from 'vue';
import NuxtJsonld from 'nuxt-jsonld';

Vue.use(NuxtJsonld);
```

I'm curious if it's possible to do this _only_ in the components that need access to this module? For example:

```
// components/componentThatUsesJsonLd.vue
<script>
import Vue from 'vue';
import NuxtJsonld from 'nuxt-jsonld';

name: 'componentThatUsesJsonLd',
...
created(){
  Vue.use(NuxtJsonld);
},
jsonld() {
...jsonld stuff
}
</script>
```

I have had success doing this with other packages like `vue-scrollactive` but in my limited testing, this did not seem to work.

**Comment by ymmooot** [comment]
Hi @t1mwillis ✋ 
This plugin uses `beforeCreate` to work `jsonld` method of a component. (source code is [here](https://github.com/ymmooot/nuxt-jsonld/blob/62f36a9fd274de4c8dde9261a3ed99f6f5be64be/src/createMixin.ts#L20))
So you have to load the plugin **before** inialization of the component.

**Comment by t1mwillis** [comment]
@ymmooot thank you for your work on this project and taking the time to answer my question.

I'll play around with other options that might be able to leverage this hook, perhaps a parent component could load it for the child.

Is it possible that we could use a different hook? Or is `beforeCreate` required because of the SSR nature of this?
