### ISSUE TITLE
Random hid issue

### ISSUE THREAD

**Issue by TrurlMcByte** [ymmooot/nuxt-jsonld#58]
In version 1.4.0 you use ```hid = "nuxt-jsonld-" + counter;```, but when I use generator
it's making "different" pages every time (because concurrently generated many pages and for each page counter every time is different)
Like this (all spaces replaced by new lines in generated html)
```diff
+++ index.html<>2019-07-02 18:13:05.732914367 +0300
@@ -92,7 +92,7 @@
  rel="manifest"
  href="/_nuxt/manifest.103da7e7.json"><script
  data-n-head="true"
- data-hid="nuxt-jsonld-20"
+ data-hid="nuxt-jsonld-0"
  type="application/ld+json">
 {
```
In this case md5 sum of page (and ETag) every times changed for stale pages.
It's possible to avoid this problem?

**Comment by ymmooot** [comment]
@TrurlMcByte Thank you for reporting issue!
I understood your problem.
I will fix this asap. 🙏
