### ISSUE TITLE
Help wanted (doubt) - components and json-ld

### ISSUE THREAD

**Issue by CavalcanteLeo** [ymmooot/nuxt-jsonld#639]
This might be a pretty silly question, but I'm completely newbie for jpso-ld and SEO.

Let's assume I have 2 components, `navigation.vue` and `companies.vue` and 1 page `index.vue` and each of these 3 needs some json-ld data.

`index.vue`
```vue
<template>
    <navigation />   <!-- component navigation has json-ld inside -->


    <companies />   <!-- component companies has json-ld inside -->

    <div>
          <!--  more content here will also have json-ld -->
    <div>
  
</template>

```

Do I have to write in only 1 place? or can i have multiples json-ld(one for each component) rendered in the same page?
Or even more, when I generate a static site, will one overwrite the others? will they merge?

**Comment by ymmooot** [comment]
You can have multiples components that having `jsonld` method.
They create multiple script tags for JSON-LD, each tag is reactive with the corresponding component.

**Comment by CavalcanteLeo** [comment]
amazing, thanks for your explanation
