### ISSUE TITLE
jsonld is showing when i "inspect' the code, but not in 'page source'

### ISSUE THREAD

**Issue by bigoper** [ymmooot/nuxt-jsonld#72]
# env
- Nuxt.js v2.8.1

# status
- I've followed the installation instructions (plugin, nuxt-config)
- I can see the jsonld data when I 'inspect' the page, but it won't show when I browse the page source. so, Google structure test tool won't recognize it.

## data()
```js
data() {
    return {
      page: 'home',
      blok: {},
      idx: {},
      myJsonld: {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'Your Organization Name',
        url: 'http://www.your-site.com',
        sameAs: ['http://www.facebook.com/your-profile', 'http://www.twitter.com/yourProfile', 'http://plus.google.com/your_profile']
      }
    }
  }
```
### jsonld()
```js
jsonld() {    
    return this.myJsonld
  }
```

### image 1: inspect
https://pasteboard.co/IoVJkfr.png

### image 1: view source
https://pasteboard.co/IoVK2mI.png

**Comment by ymmooot** [comment]
@bigoper
You have to do server-side rendering if you want to return html response with jsonld tag.
Your application looks running `spa` mode.
