### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by lazercaveman** [ymmooot/nuxt-jsonld#763]
Hello, is it planned to add support for Nuxt 3 and composition api in near future?

**Comment by ymmooot** [comment]
Hi @lazercaveman.
I have a plan to make a new version for Nuxt3 and composition api within the next few months.
Please wait for it 🙏

**Comment by niklasfjeldberg** [comment]
Any @lazercaveman update on this?

**Comment by ymmooot** [comment]
Sorry for the delay.
I am working on this at https://github.com/ymmooot/nuxt-jsonld/tree/nuxt3 and it will be finished soon.
Please wait for the release.

**Comment by ymmooot** [comment]
I have just released the new version of `nuxt-jsonld` for Nuxt3 and it has composition api.
Please try the new version and give me feedback.
Thank you for waiting.

**Comment by Right-Brain-Group** [comment]
Link to repo not working.

**Comment by Raklon181995** [comment]
@ymmooot this link is not working

**Comment by ymmooot** [comment]
Why do you need the link?
It has been already released.

**Comment by torressam333** [comment]
Is this currently working? Do I need to install the new nuxt-jsonld package?
Thanks

**Comment by ymmooot** [comment]
Hi @torressam333.
`nuxt-jsonld` 2.x is for nuxt3.
`nuxt-jsonld` 1.x is for nuxt2.
They are both working.

**Comment by torressam333** [comment]
@ymmooot ok I registered as a module like the docs show but when I try to register a `json` option in the `script[]` option in `nuxt.config.ts` I get a TS error:

```
Type '{ type: "application/ld+json"; json: { "@context": string; "@type": string; name: string; legalName: string; url: string; logo: string; foundingDate: string; founders: { "@type": string; name: string; }[]; address: { ...; }; contactPoint: { ...; }; sameAs: string[]; }; }' is not assignable to type 'string | { [x: `data-${string}`]: Stringable | undefined; async?: Booleanable | undefined; crossorigin?: "" | "anonymous" | "use-credentials" | undefined; defer?: Booleanable | undefined; ... 23 more ...; tagDuplicateStrategy?: "replace" | ... 1 more ... | undefined; } | { ...; } | { ...; } | { ...; } | undefined'.
  Object literal may only specify known properties, and 'json' does not exist in type '{ [x: `data-${string}`]: Stringable | undefined; async?: Booleanable | undefined; crossorigin?: "" | "anonymous" | "use-credentials" | undefined; defer?: Booleanable | undefined; ... 23 more ...; tagDuplicateStrategy?: "replace" | ... 1 more ... | undefined; } | { ...; } | { ...; } | { ...; }'.ts(2322)
```

Do you have a concrete example of how to use `json:{}` inside of `script[]` ?

**Comment by ymmooot** [comment]
I don't understand the meaning of `json:{}` inside of `script[]`.
There is an example already. 
https://github.com/ymmooot/nuxt-jsonld/tree/master/packages/example
