### ISSUE TITLE
Error: Cannot find module '@nuxt/kit'

### ISSUE THREAD

**Issue by shash7** [ymmooot/nuxt-jsonld#860]
Seems like you forgot to add this in your package.json
Adding it to my project makes it work.

I'm using nuxt-jsonld with nuxt v2 btw.

**Comment by ymmooot** [comment]
Hi @shash7.
Nuxt v3 includes `@nuxt/kit` and `nuxt-jsonld@v2` does not support Nuxt v2.

**Comment by shash7** [comment]
Got it. Works fine with the 1.x releases.
