### ISSUE TITLE
Nuxt-jsonld + TypeScript

### ISSUE THREAD

**Issue by oscarhandsome** [ymmooot/nuxt-jsonld#887]
Hi everyone, thanks owners for this plugin!

Please help me, or suggest a way of solving this issue related to a TS.

**package.json**
```
"dependencies": {
...
    "nuxt": "^2.15.7",
    "nuxt-jsonld": "1.5.3",
...
}
"devDependencies": {
...
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0",
...
}
```
I made all steps [here ](https://github.com/ymmooot/nuxt-jsonld/blob/v1/README.md)
and got these results:
How do I need correctly to inject it into my project?
![image](https://user-images.githubusercontent.com/8983274/173570712-efd511bc-9cb5-4c86-9a5c-366eebaedb8b.png)

I have above this, but it does not help, also I got many errors related to other variables in my app, but I used them almost everywhere declarations:

```
declare module 'vue/types/vue' {
  interface Vue {
...
    jsonld(): any
  }
}
```
![image](https://user-images.githubusercontent.com/8983274/173571371-b17a3cab-8e31-41be-b623-71de636968cc.png)

upd:
I added to jsonld:
```
jsonld(): any { 
...
}
```
Because i don't have yet strong structure, this solved my first warning, but why it broke fetch() and asyncData(), still can't understand.

**Comment by ymmooot** [comment]
Hi @oscarhandsome.
Does the`this.navigationNuxt` have a type that is not `any` or `unkown`?

**Comment by oscarhandsome** [comment]
@ymmooot i found solution!
[This helped](https://github.com/wagerfield/nuxt-typescript/issues/6) to me + this [code](https://codesandbox.io/s/1q478mzyvj?file=/tsconfig.json:608-679):
I added into **tsconfig.json**
```
"include": [
    "./index.d.ts", 
    "./**/*.ts",
    "./**/*.vue"
  ],
```
But now I don't understand for what I need [nuxt/typescript](https://github.com/nuxt/typescript) if it's not works after installing your package.

**Comment by ymmooot** [comment]
There is a minimum example of TS & nuxt-jsonld [here](https://github.com/ymmooot/nuxt-jsonld/blob/9baa1ff5093d3a54ea5d76457e1088acb63147c0/examples/typescript/pages/index.vue).

You should make a minimum reproduction code with codesandbox.
It doesn't have to be all your code, as long as you can reproduce the problem.
