### ISSUE TITLE
Cant generate JSONLD on SSR Mode

### ISSUE THREAD

**Issue by tataputri** [ymmooot/nuxt-jsonld#927]
Hi, i've trying to use this module to generate jsonld on my web,
somehow it run perfectly on DEV, but when i build it and run it on NODE Server, it

on my jsonld i use data from external API, using asyncData
![image](https://user-images.githubusercontent.com/105484949/183475565-b9f4bf07-2333-4504-a77b-7e0b86166420.png)

please help me with this one. because it broke the page and the data is failed to show

**Comment by ymmooot** [comment]
Hi @tataputri, please give me a reproduction link using [codesandbox.io](https://codesandbox.io/).

**Comment by ymmooot** [comment]
no response

**Comment by homerjam** [comment]
Hi, same problem here - works fine in dev mode but the application/ld+json script tag is missing in prod

Sandbox:
https://codesandbox.io/s/serverless-shadow-kzqp5j?file=/pages/index.vue

Deployed:
https://csb-kzqp5j.vercel.app/

**Comment by homerjam** [comment]
Related #1085 ?
