### ISSUE TITLE
"Does not provide an export named 'default'" After updating to Nuxt3 rc.8

### ISSUE THREAD

**Issue by kstraszewski** [ymmooot/nuxt-jsonld#932]
Hi, after upgrading to Nuxt3 RC8. I'm getting this error:

Uncaught SyntaxError: The requested module '/node_modules/nuxt-jsonld/dist/runtime/plugin.js' does not provide an export named 'default' (at client.mjs:5:8)

**Comment by ymmooot** [comment]
Hi @kstraszewski, thank you for reporting.
