### ISSUE TITLE
ERROR  Cannot start nuxt:  No "exports" main defined in /node_modules/nuxt-jsonld/package.json

### ISSUE THREAD

**Issue by avxkim** [ymmooot/nuxt-jsonld#940]
`"nuxt": "^3.0.0-rc.4"`

Installed:

`yarn add nuxt-jsonld`

Then trying to start in develop mode and getting an error: "ERROR  Cannot start nuxt:  No "exports" main defined in /node_modules/nuxt-jsonld/package.json"

**Comment by ymmooot** [comment]
Hi @avxkim, please update your nuxt to `3.0.0-rc.8`.
It will be resolved.

**Comment by homerjam** [comment]
Hello,

I have this error if I attempt to use the module with nuxt-bridge (nuxi `3.0.0-rc.8`) - is there another possible solution or are 
we limited to `v1` using nuxt-bridge?

Thanks
