### ISSUE TITLE
Can't pass type 'Graph' to useJsonLd function

### ISSUE THREAD

**Issue by f3oall** [ymmooot/nuxt-jsonld#963]
**Describe the bug**
Can't pass object of type 'Graph' to `useJsonLd` function. As far as I understand the `JsonLD` type doesn't include `Graph`.

**Your Nuxt version**
Nuxt 3 rc 9

**Your nuxt-jsonld version**
"^2.0.5"

**To Reproduce**
Try to pass object with type 'Graph' (see the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/1751835/189467055-753f177c-62c9-4dde-839c-c91fb91c0c57.png)

**Additional context**
N/A

**Comment by ymmooot** [comment]
Fixed by #964 and v2.0.6 has been released.
